name: feetback
description: A sensory prosthesis neurologic feedback project for the feet.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_blue_plus: ^1.32.7
  provider: ^6.1.2
  permission_handler: ^11.3.1
  hex: ^0.2.0
  convert: ^3.1.1
  collection: ^1.18.0
  flutter_svg: ^2.0.10+1
  rxdart: ^0.27.7
  sqflite: ^2.3.3+1
  path: ^1.9.0
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  scidart: ^0.0.2-dev.12
  get_it: ^7.7.0
  flutter_intl: ^0.0.1
  flutter_native_splash: ^2.4.0
  community_charts_flutter: ^1.0.3

dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/sole.svg
    - assets/sole_mask_left.svg
    - assets/sole_mask_right.svg

  uses-material-design: true

flutter_intl:
  enabled: true